--Trigger #1.

CREATE OR REPLACE TRIGGER HOUSEUPDATE
BEFORE INSERT ON HOUSE
FOR EACH ROW
DECLARE
    varHousesListed NUMBER;
BEGIN
    SELECT HOUSESLISTED INTO varHousesListed
    FROM AGENT
    WHERE ID = :NEW.AGENTID;

    IF varHousesListed >= 4 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Agent is too busy!');
    END IF;

    UPDATE AGENT
    SET HOUSESLISTED = HOUSESLISTED + 1
    WHERE ID = :NEW.AGENTID;
END;
/




-- Trigger 2
CREATE OR REPLACE TRIGGER DELETEHOUSE
AFTER DELETE ON HOUSE
FOR EACH ROW
BEGIN
    UPDATE AGENT
    SET HOUSESLISTED = HOUSESLISTED - 1
    WHERE ID = :OLD.AGENTID;
END;
/
